CREATE TABLE "instrumentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "descricao" text,
  "preco" numeric NOT NULL,
  "ano_fabricacao" integer,
  "categoria" varchar NOT NULL,
  "marca" varchar,
  "qtd_estoque" integer NOT NULL DEFAULT 0,
  "fabricado_em_mari" boolean DEFAULT false
);

CREATE TABLE "clientes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "telefone" varchar,
  "cpf" varchar UNIQUE NOT NULL,
  "endereco" varchar,
  "cidade" varchar,
  "estado" varchar,
  "torce_flamengo" boolean DEFAULT false,
  "assiste_op" boolean DEFAULT false
);

CREATE TABLE "vendedores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "telefone" varchar,
  "cpf" varchar UNIQUE NOT NULL,
  "data_admissao" date
);

CREATE TABLE "compras" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" integer NOT NULL,
  "id_vendedor" integer NOT NULL,
  "data_compra" date NOT NULL,
  "valor_total" numeric NOT NULL,
  "status_compra" varchar NOT NULL DEFAULT 'pendente',
  "desconto_aplicado" numeric DEFAULT 0
);

CREATE TABLE "itens_compra" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_compra" integer NOT NULL,
  "id_instrumento" integer NOT NULL,
  "qtd_item" integer NOT NULL,
  "preco_unitario" numeric NOT NULL
);

CREATE TABLE "pagamentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_compra" integer UNIQUE NOT NULL,
  "data_pagamento" date,
  "status_pagamento" varchar NOT NULL DEFAULT 'pendente',
  "id_forma_pagamento" integer NOT NULL
);

CREATE TABLE "formas_pagamento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "descricao" varchar UNIQUE NOT NULL
);

ALTER TABLE "compras" ADD FOREIGN KEY ("id_cliente") REFERENCES "clientes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras" ADD FOREIGN KEY ("id_vendedor") REFERENCES "vendedores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "itens_compra" ADD FOREIGN KEY ("id_compra") REFERENCES "compras" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "itens_compra" ADD FOREIGN KEY ("id_instrumento") REFERENCES "instrumentos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "compras" ADD FOREIGN KEY ("id") REFERENCES "pagamentos" ("id_compra") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pagamentos" ADD FOREIGN KEY ("id_forma_pagamento") REFERENCES "formas_pagamento" ("id") DEFERRABLE INITIALLY IMMEDIATE;
